### PR TITLE
Split: 'Installation/Get started' and 'Reference'

### PR DESCRIPTION
**Pull request by bahmady**
### Context

This README is "non-standard" from a Ruby documentation perspective, given that this information does not yet exist anywhere else, but we're going to run with this alongside more standard documentation to be implemented later 

@arnau and I have discussed splitting the two sections before we do UR on this which is what this PR covers

If you could review this @arnau and let me know what your thoughts are: it doesn't exactly match what we discussed, I know, but I can make changes as usual based on discussions

### CODE REVIEW

**Comment by bahmady** [comment]
Thanks Arnau! 

Do we not think it might be a bit problematic though that the "Collections" header we give an intro to `ItemCollection`, `EntryCollection`, and `RecordCollection`, but then go on to talk about:

`EntryCollection`
`RecordCollection`
`RecordMapCollection`
`Item`
`Entry`
`Record`

?

**Comment by arnau** [comment]
You are right, the last three should be either under their own collection or outside collections altogether

**Comment by bahmady** [comment]
Separately is it also all right that we don't have a section for `ItemCollection`?

**Comment by arnau** [comment]
I think `ItemCollection` should be treated the same way as the other two collections. The rest looks good.

**Pull request merged**
