### PR TITLE
Upgrade Ruby to 2.5.0

### PR DESCRIPTION
**Pull request by karlbaker02**
### Context

This PR upgrades Ruby from version 2.4.2 to 2.5.0.

### CODE REVIEW

**Comment by danmitchell-** [comment]
No changes in `gemfile.lock`?

**Comment by karlbaker02** [comment]
No changes.

**Comment by gidsg** [comment]
Does this mean people using the gem will need to be on this ruby version?

**Comment by karlbaker02** [comment]
It does @gidsg.

**Comment by karlbaker02** [comment]
Or higher.

**Comment by danmitchell-** [comment]
I don't think that is true actually. The gemspec sets the "rules" for dependancy versions. `.ruby-version` only sets the ruby version via rvm etc in development

**Comment by karlbaker02** [comment]
Actually, yes, you're right Dan.

**Pull request merged**
