### PR TITLE
Organisation of information

### PR DESCRIPTION
**Pull request by bahmady**
Currently we have three separate main sections:

"Items, entries, and records"
"Collections"
and the placeholder, "Accessing methods"

Can any of the methods under "accessing methods" be grouped under other titles? Or can we have a more descriptive title for "Accessing methods" such as "Other methods"? I'm open to all suggestions but don't want to make too many edits without context.

### Context

Need to better understand how to arrange the information in the README, and the biggest and most obvious issue at the moment seems to be how the information about classes is arranged

### Changes proposed in this pull request

I've changed "Accessing methods" to "Other methods" more to stimulate conversation in this PR than anything else 

### Guidance to review

N/A

### CODE REVIEW

**Comment by bahmady** [comment]
@karlbaker02 I'm happy to defer to you however you want the info organised, just to be clear.

What I am getting confused about is the fact that it seems to me like many of the methods (i.e. not only those currently under the "Accessing methods" header) could be grouped under a new header, `RegisterClient`. Is that not so?

**Comment by karlbaker02** [comment]
@bahmady Which methods would you consider moving under a new `RegisterClient` heading? For me, `RegisterClient` is very specific as meaning all of the methods that are publicly available on that class. The `RegisterClient` class does return other types, such as `Item`, `Entry` and `Record` as described earlier in the README, but it feels right that these are documented in their own sections as they are separate classes.

**Comment by arnau** [comment]
@bahmady not really. `RegisterClient` is not a collection so it doesn't respond to `each`.

**Comment by bahmady** [comment]
OK, @arnau and I had a chat about this and it makes more sense now. Sorry for the confusion, @karlbaker02 

I'll make the header title `RegisterClient` rather than "Other methods" 

Are there any new (undocumented) methods in https://github.com/openregister/registers-ruby-client/blob/master/lib/register_client.rb ?

**Comment by karlbaker02** [comment]
@bahmady There may be. I'll put some time aside to go through what is new this week.

**Pull request merged**
